window.ENV = {
  SUPABASE_URL: "https://your-project.supabase.co",
  SUPABASE_ANON_KEY: "your-supabase-publishable-or-anon-key",
  AUTH_STORAGE_KEY: "lbpro_supabase_auth",
  SITE_PUBLIC_URL: "http://localhost:4222",
  PUBLIC_STATE_BASE_URL: "https://your-vercel-domain.vercel.app",
  PUBLIC_LEADERBOARD_BASE_URL: "https://your-vercel-domain.vercel.app",
  PUBLIC_LIVE_BASE_URL: "https://your-vercel-domain.vercel.app/",
  PUBLIC_SNAPSHOT_POLL_MS: 15000,
  PUBLIC_SNAPSHOT_REALTIME_ENABLED: false,
  PUBLIC_SNAPSHOT_DIRECT_SUPABASE_FALLBACK: false,
  LOCAL_SNAPSHOT_SERVER_URL: "",
  OPERATOR_SCORE_POLL_MS: 10000,
  OPERATOR_SNAPSHOT_AUTO_PUBLISH_MS: 10000,
  OPERATOR_PARTICIPANT_POLL_MS: 60000,
  OPERATOR_CATALOG_POLL_MS: 60000,
  PUBLIC_STATE_REVALIDATE_URL: "",
  PUBLIC_STATE_REVALIDATE_TOKEN: "",
  LOCAL_OCR_ENDPOINT: "http://localhost:8866/ocr",
  GEMINI_SCORECARD_ENDPOINT: "http://localhost:8866/gemini-scorecard-ocr",
  OCR_MAX_IMAGE_SIDE: 1800,
  GOOGLE_AI_STUDIO_ENDPOINT: "",
  GOOGLE_AI_STUDIO_API_KEY: "",
  DEFAULT_SYNC_MODE: "local",
  LB_RUNTIME_MODE: "local",
  LB_RUNTIME_CLIENT: "local",
  LB_CLOUD_AUTH_DOMAIN: "operator.system36.app"
};
